interface Task {
  id: string;
  title: string;
  description: string;
  estimated_effort_hours: number;
  dependencies: string[];
  suggested_tech: string;
  ai_agent_prompt_hint: string;
  no_code_platform_hint: string;
}

interface Phase {
  id: string;
  title: string;
  description: string;
  tasks: Task[];
}

interface PlanContent {
  plan_name: string;
  phases: Phase[];
}

export function generateNoCodeBlueprint(planContent: PlanContent): string {
  let markdown = `# No-Code Blueprint: ${planContent.plan_name}

`;

  markdown += `## Overview\n${planContent.plan_name} is designed to be built with a focus on rapid development using no-code principles.\n\n`;

  markdown += `## Data Models\n`;
  // This part would ideally infer data models from tasks or a separate schema
  // For now, a placeholder based on common app ideas
  markdown += `- **Users**: Email, Password (handled by auth service)\n`;
  markdown += `- **App Ideas**: Title, Purpose, Target Audience, Features, Tech Stack, Resources\n`;
  markdown += `- **Build Plans**: Name, Status, Current Revision\n`;
  markdown += `- **Plan Revisions**: Content (JSON), Generated by AI, Editor User\n\n`;

  markdown += `## Workflows & UI Components\n`;
  planContent.phases.forEach((phase) => {
    markdown += `### Phase: ${phase.title}\n`;
    markdown += `- Description: ${phase.description}\n\n`;

    phase.tasks.forEach((task) => {
      markdown += `#### Task: ${task.title}\n`;
      markdown += `- **Description**: ${task.description}\n`;
      if (task.no_code_platform_hint) {
        markdown += `- **No-Code Hint**: ${task.no_code_platform_hint}\n`;
      }
      markdown += `- **Suggested UI/Workflow**: Consider using drag-and-drop builders for UI, and visual workflow editors for logic.\n\n`;
    });
  });

  return markdown;
}
